# Copyright IBM Corp, 2016
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied. See the License for the specific language governing
# permissions and limitations under the License.

---
- name: Create slave directory
  file: >
    path=/var/powerci/slave
    state=directory

- name: Create debian_jessie directory
  file: >
    path=/var/powerci/slave/debian_jessie
    state=directory

- name: Copy Dockerfile
  copy: >
    src=Dockerfile.debian_jessie
    dest=/var/powerci/slave/debian_jessie/Dockerfile

- name: Copy authorized_keys
  copy: >
    src=authorized_keys
    dest=/var/powerci/slave/debian_jessie/authorized_keys
    owner={{ ansible_user }}
    mode=0644

- name: Build debian jessie image
  docker_image: >
    name={{ debian.name }}
    path={{ debian.path }}
    state=present

- name: Start debian jessie container
  docker_container:
    name: "debian{{ item }}"
    image: "{{ debian.name }}"
    state: started
    ports:
      - "{{ debian.ports[ item|int ] }}:22"
  with_sequence: start=0 count={{ debian.ports|length }}

- name: Counting debian containers
  shell: docker ps -f name=debian* | tail -n +2 | wc -l
  register: up_debians

- name: Remove exceding containers
  docker_container:
    name: "debian{{ item }}"
    state: absent
  with_sequence: >
    start={{ debian.ports|length }}
    count={{ (up_debians.stdout|int)-(debian.ports|length) }}
  when: up_debians.stdout|int > debian.ports|length

- name: Create ubuntu_16_04 directory
  file: >
    path=/var/powerci/slave/ubuntu_16_04
    state=directory

- name: Copy Dockerfile
  copy: >
    src=Dockerfile.ubuntu_16_04
    dest=/var/powerci/slave/ubuntu_16_04/Dockerfile

- name: Copy authorized_keys
  copy: >
    src=authorized_keys
    dest=/var/powerci/slave/ubuntu_16_04/authorized_keys
    owner={{ ansible_user }}
    mode=0644

- name: Build ubuntu 16.04 image
  docker_image: >
    name={{ ubuntu.name }}
    path={{ ubuntu.path }}
    state=present

- name: Start ubuntu 16.04 container
  docker_container:
    name: "ubuntu{{ item }}"
    image: "{{ ubuntu.name }}"
    state: started
    ports:
      - "{{ ubuntu.ports[ item|int ] }}:22"
  with_sequence: start=0 count={{ ubuntu.ports|length }}

- name: Counting ubuntu containers
  shell: docker ps -f name=ubuntu* | tail -n +2 | wc -l
  register: up_ubuntus

- name: Remove exceding containers
  docker_container:
    name: "ubuntu{{ item }}"
    state: absent
  with_sequence: >
    start={{ ubuntu.ports|length }}
    count={{ (up_ubuntus.stdout|int)-(ubuntu.ports|length) }}
  when: up_ubuntus.stdout|int > ubuntu.ports|length

- name: Remove stopped containers
  shell: docker rm `docker ps -q -f status=exited`
  failed_when: False

- name: Remove dangling images
  shell: docker rmi `docker images -q -f dangling=true`
  failed_when: False
